apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-api-service"
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" }}
spec:
  ports:
    - name: ex-service-template-api
      port: 80
      targetPort: 8000
  selector:
    app: "{{ .Chart.Name }}-api"
    app.kubernetes.io/component: service